spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/authservice_spotube
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 88729266452-ka82hs4lfsfv9u96kqp6fuvkdpvm6eae.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

  jpa:
    hibernate:
      ddl-auto: update   # tạo/sync bảng tự động (update, create, create-drop, validate)
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8082 # port riêng cho auth-service

jwt:
  signerKey : "Q+W+8at86K9vMPRa3ZZEHWOL6wiQzDmNS0X9Wu8omL2h5qgfIIb0oEchMm+v49MP"

user-service:
  create-path: http://user-service/users/create