spring:
  datasource:
    url: jdbc:h2:mem:auth;DB_CLOSE_DELAY=-1    # DB chạy trong RAM, mỗi lần restart reset
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email, profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
# endpoint login gg: http://localhost:8080/login/oauth2/code/google

  jpa:
    hibernate:
      ddl-auto: update   # tạo/sync bảng tự động (update, create, create-drop, validate)
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

server:
  port: 8080 # port riêng cho auth-service

jwt:
  signerKey : "Q+W+8at86K9vMPRa3ZZEHWOL6wiQzDmNS0X9Wu8omL2h5qgfIIb0oEchMm+v49MP"

user-service:
  create-path: http://user-service/users/create