spring.application.name=playing-service
server.port=4001

### Eureka (canonical form)
eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
#spotube.jwt.shared_secret=secret_key_change_me_please_32_bytes_min
## CloudFront signer
#spotube.aws.pvtkeyPath=classpath:static/private_key.der
#spotube.aws.cloudfront.distributionDomainName=d6puu73zzo17e.cloudfront.net
#spotube.aws.cloudfront.keypairId=K1W74YMJ2QWWV5
#spotube.aws.cloudfront.urlTtlSeconds=120
#spotube.aws.objectPrefix=tracks/
