spring.application.name=upload-serivce
server.port=4002

#cloud.aws.credentials.access-key=AKIAV7OFB7777OP5V2XK
#cloud.aws.credentials.secret-key=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
#cloud.aws.region.static=ap-southeast-2

#aws.bucket.name=spotube

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

#spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer
