
### ----------------------------------------------------------------
### Variables (edit these)
### ----------------------------------------------------------------
@baseUrl = http://localhost:4001
@trackId = 1

@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyXzAwMDAwMSIsImF1dGhvcml0aWVzIjpbIlJPTEVfVVNFUiJdLCJpYXQiOjE3NTgzMzY1NzksImV4cCI6MTc1ODM0MDE3OX0.5oI4ETPoqjbLwX7M7SoDPVE3qrwMQghj49BocfAum78
### ----------------------------------------------------------------
### 1) Get signed CloudFront URL for a track
### ----------------------------------------------------------------
# @name PlaySignedUrl
POST {{baseUrl}}/play
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "track_id": "{{trackId}}"
}

### ----------------------------------------------------------------
### 2) Negative test: missing/invalid token should be 401/403
### ----------------------------------------------------------------
# @name PlayUnauthorized
POST {{baseUrl}}/play
Content-Type: application/json

{
  "track_id": "{{trackId}}"
}
