spring.application.name=recommend-service

server.port=4008

insighttune.jwt.shared_secret=Q+W+8at86K9vMPRa3ZZEHWOL6wiQzDmNS0X9Wu8omL2h5qgfIIb0oEchMm+v49MP

eureka.client.serviceUrl.defaultZone=http://eureka-service:8761/eureka/
